// bpf_default_slv.v

// Generated using ACDS version 23.4 79

`timescale 1 ps / 1 ps
module bpf_default_slv (
		input  wire        clk,       //                 clock.clk
		input  wire        rst_n,     //                 reset.reset_n
		input  wire [5:0]  s_awaddr,  // altera_axi4lite_slave.awaddr
		input  wire [2:0]  s_awprot,  //                      .awprot
		input  wire        s_awvalid, //                      .awvalid
		output wire        s_awready, //                      .awready
		input  wire [63:0] s_wdata,   //                      .wdata
		input  wire [7:0]  s_wstrb,   //                      .wstrb
		input  wire        s_wvalid,  //                      .wvalid
		output wire        s_wready,  //                      .wready
		output wire [1:0]  s_bresp,   //                      .bresp
		output wire        s_bvalid,  //                      .bvalid
		input  wire        s_bready,  //                      .bready
		input  wire [5:0]  s_araddr,  //                      .araddr
		input  wire [2:0]  s_arprot,  //                      .arprot
		input  wire        s_arvalid, //                      .arvalid
		output wire        s_arready, //                      .arready
		output wire [63:0] s_rdata,   //                      .rdata
		output wire [1:0]  s_rresp,   //                      .rresp
		output wire        s_rvalid,  //                      .rvalid
		input  wire        s_rready   //                      .rready
	);

	axi4lite_rsp #(
		.AW         (6),
		.DW         (64),
		.WSTRB_W    (8),
		.RSP_VALUE  (64'b0000000000000000000000000000000000000000000000000000000000000000),
		.RSP_STATUS (2'b00)
	) bpf_default_slv (
		.clk       (clk),       //   input,   width = 1,                 clock.clk
		.rst_n     (rst_n),     //   input,   width = 1,                 reset.reset_n
		.s_awaddr  (s_awaddr),  //   input,   width = 6, altera_axi4lite_slave.awaddr
		.s_awprot  (s_awprot),  //   input,   width = 3,                      .awprot
		.s_awvalid (s_awvalid), //   input,   width = 1,                      .awvalid
		.s_awready (s_awready), //  output,   width = 1,                      .awready
		.s_wdata   (s_wdata),   //   input,  width = 64,                      .wdata
		.s_wstrb   (s_wstrb),   //   input,   width = 8,                      .wstrb
		.s_wvalid  (s_wvalid),  //   input,   width = 1,                      .wvalid
		.s_wready  (s_wready),  //  output,   width = 1,                      .wready
		.s_bresp   (s_bresp),   //  output,   width = 2,                      .bresp
		.s_bvalid  (s_bvalid),  //  output,   width = 1,                      .bvalid
		.s_bready  (s_bready),  //   input,   width = 1,                      .bready
		.s_araddr  (s_araddr),  //   input,   width = 6,                      .araddr
		.s_arprot  (s_arprot),  //   input,   width = 3,                      .arprot
		.s_arvalid (s_arvalid), //   input,   width = 1,                      .arvalid
		.s_arready (s_arready), //  output,   width = 1,                      .arready
		.s_rdata   (s_rdata),   //  output,  width = 64,                      .rdata
		.s_rresp   (s_rresp),   //  output,   width = 2,                      .rresp
		.s_rvalid  (s_rvalid),  //  output,   width = 1,                      .rvalid
		.s_rready  (s_rready)   //   input,   width = 1,                      .rready
	);

endmodule
