// bpf_emif_slv.v

// Generated using ACDS version 23.4 79

`timescale 1 ps / 1 ps
module bpf_emif_slv (
		input  wire        clk,       //                  clock.clk
		input  wire        rst_n,     //                  reset.reset_n
		input  wire [11:0] s_awaddr,  //  altera_axi4lite_slave.awaddr
		input  wire [2:0]  s_awprot,  //                       .awprot
		input  wire        s_awvalid, //                       .awvalid
		output wire        s_awready, //                       .awready
		input  wire [63:0] s_wdata,   //                       .wdata
		input  wire [7:0]  s_wstrb,   //                       .wstrb
		input  wire        s_wvalid,  //                       .wvalid
		output wire        s_wready,  //                       .wready
		output wire [1:0]  s_bresp,   //                       .bresp
		output wire        s_bvalid,  //                       .bvalid
		input  wire        s_bready,  //                       .bready
		input  wire [11:0] s_araddr,  //                       .araddr
		input  wire [2:0]  s_arprot,  //                       .arprot
		input  wire        s_arvalid, //                       .arvalid
		output wire        s_arready, //                       .arready
		output wire [63:0] s_rdata,   //                       .rdata
		output wire [1:0]  s_rresp,   //                       .rresp
		output wire        s_rvalid,  //                       .rvalid
		input  wire        s_rready,  //                       .rready
		output wire [11:0] m_awaddr,  // altera_axi4lite_master.awaddr
		output wire [2:0]  m_awprot,  //                       .awprot
		output wire        m_awvalid, //                       .awvalid
		input  wire        m_awready, //                       .awready
		output wire [63:0] m_wdata,   //                       .wdata
		output wire [7:0]  m_wstrb,   //                       .wstrb
		output wire        m_wvalid,  //                       .wvalid
		input  wire        m_wready,  //                       .wready
		input  wire [1:0]  m_bresp,   //                       .bresp
		input  wire        m_bvalid,  //                       .bvalid
		output wire        m_bready,  //                       .bready
		output wire [11:0] m_araddr,  //                       .araddr
		output wire [2:0]  m_arprot,  //                       .arprot
		output wire        m_arvalid, //                       .arvalid
		input  wire        m_arready, //                       .arready
		input  wire [63:0] m_rdata,   //                       .rdata
		input  wire [1:0]  m_rresp,   //                       .rresp
		input  wire        m_rvalid,  //                       .rvalid
		output wire        m_rready   //                       .rready
	);

	axi4lite_shim #(
		.AW      (12),
		.DW      (64),
		.WSTRB_W (8)
	) bpf_emif_slv (
		.clk       (clk),       //   input,   width = 1,                  clock.clk
		.rst_n     (rst_n),     //   input,   width = 1,                  reset.reset_n
		.s_awaddr  (s_awaddr),  //   input,  width = 12,  altera_axi4lite_slave.awaddr
		.s_awprot  (s_awprot),  //   input,   width = 3,                       .awprot
		.s_awvalid (s_awvalid), //   input,   width = 1,                       .awvalid
		.s_awready (s_awready), //  output,   width = 1,                       .awready
		.s_wdata   (s_wdata),   //   input,  width = 64,                       .wdata
		.s_wstrb   (s_wstrb),   //   input,   width = 8,                       .wstrb
		.s_wvalid  (s_wvalid),  //   input,   width = 1,                       .wvalid
		.s_wready  (s_wready),  //  output,   width = 1,                       .wready
		.s_bresp   (s_bresp),   //  output,   width = 2,                       .bresp
		.s_bvalid  (s_bvalid),  //  output,   width = 1,                       .bvalid
		.s_bready  (s_bready),  //   input,   width = 1,                       .bready
		.s_araddr  (s_araddr),  //   input,  width = 12,                       .araddr
		.s_arprot  (s_arprot),  //   input,   width = 3,                       .arprot
		.s_arvalid (s_arvalid), //   input,   width = 1,                       .arvalid
		.s_arready (s_arready), //  output,   width = 1,                       .arready
		.s_rdata   (s_rdata),   //  output,  width = 64,                       .rdata
		.s_rresp   (s_rresp),   //  output,   width = 2,                       .rresp
		.s_rvalid  (s_rvalid),  //  output,   width = 1,                       .rvalid
		.s_rready  (s_rready),  //   input,   width = 1,                       .rready
		.m_awaddr  (m_awaddr),  //  output,  width = 12, altera_axi4lite_master.awaddr
		.m_awprot  (m_awprot),  //  output,   width = 3,                       .awprot
		.m_awvalid (m_awvalid), //  output,   width = 1,                       .awvalid
		.m_awready (m_awready), //   input,   width = 1,                       .awready
		.m_wdata   (m_wdata),   //  output,  width = 64,                       .wdata
		.m_wstrb   (m_wstrb),   //  output,   width = 8,                       .wstrb
		.m_wvalid  (m_wvalid),  //  output,   width = 1,                       .wvalid
		.m_wready  (m_wready),  //   input,   width = 1,                       .wready
		.m_bresp   (m_bresp),   //   input,   width = 2,                       .bresp
		.m_bvalid  (m_bvalid),  //   input,   width = 1,                       .bvalid
		.m_bready  (m_bready),  //  output,   width = 1,                       .bready
		.m_araddr  (m_araddr),  //  output,  width = 12,                       .araddr
		.m_arprot  (m_arprot),  //  output,   width = 3,                       .arprot
		.m_arvalid (m_arvalid), //  output,   width = 1,                       .arvalid
		.m_arready (m_arready), //   input,   width = 1,                       .arready
		.m_rdata   (m_rdata),   //   input,  width = 64,                       .rdata
		.m_rresp   (m_rresp),   //   input,   width = 2,                       .rresp
		.m_rvalid  (m_rvalid),  //   input,   width = 1,                       .rvalid
		.m_rready  (m_rready)   //  output,   width = 1,                       .rready
	);

endmodule
